# Generated by Django 4.2.7 on 2026-01-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Imagem de Capa')),
                ('excerpt', models.TextField(blank=True, help_text='Breve resumo do post (até 500 caracteres)', max_length=500, verbose_name='Resumo')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('published_at', models.DateTimeField(blank=True, help_text='Data de publicação (preenchido automaticamente ao publicar)', null=True, verbose_name='Publicado em')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
