# Generated by Django

from django.db import migrations, models


# Ordem padrão discutida: 1 Válvulas, 2 Tubos, 3 Conexões, 4 Flanges, 5 Combate a Incêndio, 6 Acessórios, 7 Diversos
SLUG_ORDER = {
    "valvulas-industriais": 1,
    "tubos": 2,
    "conexoes": 3,
    "conexoes-tubulares": 3,
    "flanges": 4,
    "combate-a-incendio": 5,
    "acessorios": 6,
    "diversas": 7,
    "diversos": 7,
}
DEFAULT_ORDER = 99  # categorias não mapeadas aparecem por último


def set_category_order(apps, schema_editor):
    Category = apps.get_model("products", "Category")
    for cat in Category.objects.all():
        cat.order = SLUG_ORDER.get(cat.slug, DEFAULT_ORDER)
        cat.save(update_fields=["order"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_allow_blank_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Ordem de exibição no catálogo (menor número aparece primeiro)",
                verbose_name="Ordem",
            ),
        ),
        migrations.RunPython(set_category_order, noop),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
    ]
